faves/urls.py
from django.urls import path

from .templates.views import *

app_name = 'faves'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),

    path('', index, name='index'),
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
    path('influencers', influencers, name='influencers'),
    path('influencers/<str:influencer_id>', influencer, name='influencer'),
    path('nba', nba, name='nba'),
    path('nba/tweets', nba_tweets, name='nba_tweets'),
    path('nba/tweets/<str:sport>', add_twitter_user, name='add_twitter_user'),
    path('mlb', mlb, name='mlb'),
    path('mlb/tweets', mlb_tweets, name='mlb_tweets'),
    path('mlb/tweets/<str:sport>', add_twitter_user, name='add_twitter_user'),
    path('mlb/<str:team_name>', mlb_team, name='mlb_team'),

    # path('mlb/tweets/<str:user>', views.add_twitter_user, name='add_twitter_user'),
    #path('get_teams/', views.get_teams, name='get_teams'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^stats/', include('stats.urls')), #this line added
    url(r'^detection/', include('detection.urls')), #this line added
    url(r'^polls/', include('polls.urls')), #this line added
    url(r'^admin/', admin.site.urls),
]

stuff/urls.py
from django.urls import path

from .templates.views import *

app_name = 'stuff'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),

    path('', index, name='index'),
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
    path('influencers', influencers, name='influencers'),
    path('influencers/<str:influencer_id>', influencer, name='influencer'),
    path('nba', nba, name='nba'),
    path('nba/tweets', nba_tweets, name='nba_tweets'),
    path('nba/tweets/<str:sport>', add_twitter_user, name='add_twitter_user'),
    path('mlb', mlb, name='mlb'),
    path('mlb/tweets', mlb_tweets, name='mlb_tweets'),
    path('mlb/tweets/<str:sport>', add_twitter_user, name='add_twitter_user'),
    path('mlb/<str:team_name>', mlb_team, name='mlb_team'),

    # path('mlb/tweets/<str:user>', views.add_twitter_user, name='add_twitter_user'),
    #path('get_teams/', views.get_teams, name='get_teams'),
]

faves/templates/views/influencers.py
from django.shortcuts import render

from faves.models import Influencer, SocialMedia, Twitter, Instagram, Youtube, Facebook


def influencers(request):
    context = get_all_influencers()
    return render(request, 'faves/influencers.html', context)


def get_all_influencers():
    entertainment = get_influencers_helper('Entertainment')
    fashion = get_influencers_helper('Fashion')
    food = get_influencers_helper('Food')
    gaming = get_influencers_helper('Gaming')
    makeup = get_influencers_helper('Makeup')
    sports_fitness = get_influencers_helper('Sports/Fitness')
    travel = get_influencers_helper('Travel')
    vlogging = get_influencers_helper('Vlogging')

    all_influencers = {
        'entertainment': entertainment,
        'fashion': fashion,
        'food': food,
        'gaming': gaming,
        'makeup': makeup,
        'sports_fitness': sports_fitness,
        'travel': travel,
        'vlogging': vlogging
    }

    print("........................................")
    return all_influencers


def get_influencers_helper(industry):
    print(industry)
    # get influencers from a particular industry
    influencers_by_industry = Influencer.objects.filter(industry=industry).order_by("level")

    influencers_by_industry_map = []
    for influencer in influencers_by_industry:
        print("influencer ........................................")
        print(influencer)
        influencers_by_industry_map.append(get_influencer_map_info(influencer))

    return influencers_by_industry_map


def influencer(request, influencer_id):
    influencer = get_influencer_by_id(influencer_id)
    print("influencer ........................................")
    print(influencer)
    context = {
        'influencer': influencer
    }

    return render(request, 'faves/influencer.html', context)


def get_influencer_by_id(influencer_id):
    influencer = Influencer.objects.filter(id=influencer_id).first()
    print("influencer ........................................")
    print(influencer)
    return get_influencer_map_info(influencer)


def get_influencer_map_info(influencer):
    print("social_media_id ........................................")
    # get social_media_id of particular influencer
    social_media_id = SocialMedia.objects.filter(influencer=influencer).first()
    print(social_media_id)

    influencer_map = {
        'id': influencer.id,
        'first_name': influencer.first_name,
        'last_name': influencer.last_name,
        'nickname': influencer.nickname,
        'level': influencer.level,
        'industry': influencer.industry,
        'twitter': '',
        'instagram': '',
        'youtube': '',
        'facebook': ''
    }
    print("twitter ........................................")
    # get all social medias using social_media id
    twitter = Twitter.objects.filter(social_media=social_media_id.id).order_by("id").first()
    print(twitter)
    print(twitter.handle)

    if twitter is not None:
        influencer_map.update({'twitter': twitter.handle})

    print("instagram ........................................")
    instagram = Instagram.objects.filter(social_media=social_media_id.id).order_by("id").first()
    print(instagram)
    if instagram is not None:
        influencer_map.update({'instagram': instagram.handle})

    print("youtube ........................................")
    youtube = Youtube.objects.filter(social_media=social_media_id.id).order_by("id").first()
    print(youtube)
    if youtube is not None:
        influencer_map.update({'youtube': youtube.handle})

    print("facebook  ........................................")
    facebook = Facebook.objects.filter(social_media=social_media_id.id).order_by("id").first()
    print(facebook)
    if facebook is not None:
        influencer_map.update({'facebook': facebook.handle})

    print("........................................")
    return influencer_map

faves/templates/views/login.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def login(request):
    print(login.__name__)
    print(request)
    print(request.get_full_path())
    if request.method == 'POST':
        try:
            user = authenticate(email=request.POST.get('email', None), password=request.POST.get('password', None))
            if user is not None:
                print("Logging in")
                login_user(request, user)
                return HttpResponseRedirect(reverse('faves:index'))
            else:
                print("Cant log in")
                return HttpResponseRedirect(reverse('faves:login'))

        except Exception as err:
            print(err)
            for i in err.message:
                print(i)

    return render(request, 'faves/login.html')

faves/templates/views/mlb.py
from __future__ import print_function

import twitter
from django.shortcuts import render

from faves.models import Sport, Team
from myfaves.settings import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_CONSUMER_ACCESS_TOKEN_KEY, \
    TWITTER_CONSUMER_TOKEN_SECRET

TWITTER_API = twitter.Api(consumer_key=TWITTER_CONSUMER_KEY,
                          consumer_secret=TWITTER_CONSUMER_SECRET,
                          access_token_key=TWITTER_CONSUMER_ACCESS_TOKEN_KEY,
                          access_token_secret=TWITTER_CONSUMER_TOKEN_SECRET)

import datetime
from datetime import datetime

import mlbgame


def mlb(request):
    # mlb_teams = mlbgame.teams()
    context = {}
    context.update(get_mlb_teams())
    context.update(get_mlb_games_today())
    return render(request, 'faves/mlb.html', context)


def mlb_team(request, team_name):
    # mlb_teams = mlbgame.teams()
    print("TESTTTTTTTTTTTTTTTTT mlb_team: " + team_name)
    mlb_teams = get_mlb_teams()
    this_team = None
    for team in mlb_teams['mlb_teams']:
        if team.nickname.lower() == team_name:
            this_team = team
    print(this_team)
    context = {
        "team": this_team

    }
    return render(request, 'faves/mlb_team.html', context)


def get_mlb_teams():
    mlb = Sport.objects.filter(abbreviation="MLB").first()
    mlb_teams = Team.objects.filter(sport=mlb)

    print(mlb_teams)
    context = {
        'mlb_teams': mlb_teams
    }
    print("........................................")
    return context


def get_mlb_games_today():
    now = datetime.now()
    day = mlbgame.day(now.year, now.month, now.day)
    day.sort(key=lambda d: datetime.strptime(d.game_start_time, '%I:%M %p'), reverse=False)

    for game in day:
        print(game.game_id)
    # print(game.game_id)
    # test = mlbgame.box_score(game.game_id)
    # mlbgame.overview(game.game_id)
    # mlbgame.players(game.game_id)
    # mlbgame.team_stats(game.game_id)
    # mlbgame.player_stats(game.game_id)
    # mlbgame.game_events(game.game_id)

    print(day)
    context = {
        "games_today": day

    }
    return context


tweets_mlb = {}
tweets_mlb = set(tweets_mlb)
users_mlb = {"MLB", "Yankees", "mlbtraderumors", "Ken_Rosenthal", "JonHeymanCBS", "Buster_ESPN"}


def mlb_tweets(request):
    print(mlb_tweets.__name__)
    print(request)
    print(request.get_full_path())
    for user in users_mlb:
        data = TWITTER_API.GetUserTimeline(screen_name=user, count=5)

        for new_tweet in data:
            # print(new_tweet)
            # print(new_tweet.id)
            if not any(new_tweet.id == tweet.id for tweet in tweets_mlb):
                tweets_mlb.add(new_tweet)

    sorted_tweets_mlb = sorted(tweets_mlb, key=lambda d: datetime.strptime(d.created_at, '%a %b %d %H:%M:%S %z %Y'),
                               reverse=True)

    print(tweets_mlb)
    context = {
        'sport': "mlb",
        'tweets': sorted_tweets_mlb,
        'users': users_mlb
    }

    return render(request, 'faves/tweets.html', context)

faves/templates/views/nba.py
from __future__ import print_function

import twitter
from django.shortcuts import render

from faves.models import Sport, Team
from myfaves.settings import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_CONSUMER_ACCESS_TOKEN_KEY, \
    TWITTER_CONSUMER_TOKEN_SECRET

TWITTER_API = twitter.Api(consumer_key=TWITTER_CONSUMER_KEY,
                          consumer_secret=TWITTER_CONSUMER_SECRET,
                          access_token_key=TWITTER_CONSUMER_ACCESS_TOKEN_KEY,
                          access_token_secret=TWITTER_CONSUMER_TOKEN_SECRET)

import datetime
from datetime import datetime


def nba(request):
    context = get_nba_teams()
    return render(request, 'faves/nba.html', context)


def get_nba_teams():
    nba = Sport.objects.filter(abbreviation="NBA").first()
    nba_teams = Team.objects.filter(sport=nba).order_by("abbreviation")
    print(nba_teams)
    context = {
        'nba_teams': nba_teams
    }
    return context


tweets_nba = {}
tweets_nba = set(tweets_nba)
users_nba = {"NBA", "wojespn", "ShamsCharania", "ZachLowe_NBA", "sam_amick", "TheSteinLine", "ChrisBHaynes",
             "davidaldridgedc", "WindhorstESPN"}


def nba_tweets(request):
    print(nba_tweets.__name__)
    print(request)
    print(request.get_full_path())
    for user in users_nba:
        data = TWITTER_API.GetUserTimeline(screen_name=user, count=5)

        for new_tweet in data:
            # print(new_tweet)
            # print(new_tweet.id)
            if not any(new_tweet.id == tweet.id for tweet in tweets_nba):
                tweets_nba.add(new_tweet)

    sorted_tweets_nba = sorted(tweets_nba, key=lambda d: datetime.strptime(d.created_at, '%a %b %d %H:%M:%S %z %Y'),
                               reverse=True)

    print(tweets_nba)
    context = {
        'sport': "nba",
        'tweets': sorted_tweets_nba,
        'users': users_nba
    }

    return render(request, 'faves/tweets.html', context)

faves/templates/views/register.py
from django.shortcuts import render


def register(request):
    return render(request, 'faves/register.html')

stuff/templates/views/index.py
from django.shortcuts import render
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from stuffhub.settings import YOUTUBE_API_KEY

YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'


def index(request):
    print(index.__name__)
    print(request)
    print(request.get_full_path())
    if not request.user.is_authenticated:
        return render(request, 'stuff/login.html')

    try:
        youtube_search("JustKiddingPart")
    except HttpError as e:
        print("An HTTP error %d occurred:\n%s' % (e.resp.status, e.content)")

    return render(request, 'stuff/index.html')


def youtube_search(options):
    youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION,
                    developerKey=YOUTUBE_API_KEY)

    # Call the search.list method to retrieve results matching the specified
    # query term.
    search_response = youtube.search().list(
        q=options,
        part='id,snippet',
        maxResults=25
    ).execute()

    videos = []
    channels = []
    playlists = []

    # Add each result to the appropriate list, and then display the lists of
    # matching videos, channels, and playlists.
    for search_result in search_response.get('items', []):
        if search_result['id']['kind'] == 'youtube#video':
            videos.append('%s (%s)' % (search_result['snippet']['title'],
                                       search_result['id']['videoId']))
        elif search_result['id']['kind'] == 'youtube#channel':
            channels.append('%s (%s)' % (search_result['snippet']['title'],
                                         search_result['id']['channelId']))
        elif search_result['id']['kind'] == 'youtube#playlist':
            playlists.append('%s (%s)' % (search_result['snippet']['title'],
                                          search_result['id']['playlistId']))

    print('Videos:\n', '\n'.join(videos), '\n')
    print('Channels:\n', '\n'.join(channels), '\n')
    print('Playlists:\n', '\n'.join(playlists), '\n')

stuff/templates/views/login.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def login(request):
    print(login.__name__)
    print(request)
    print(request.get_full_path())
    if request.method == 'POST':
        try:
            user = authenticate(email=request.POST.get('email', None), password=request.POST.get('password', None))
            if user is not None:
                login_user(request, user)
                return HttpResponseRedirect(reverse('stuff:index'))
            else:
                return HttpResponseRedirect(reverse('stuff:login_view'))

        except Exception as err:
            print(err.message)
            for i in err.message:
                print(i)

    return render(request, 'stuff/login.html')

stuff/templates/views/logout.py
from django.contrib.auth import logout as logout_user
from django.shortcuts import render


def logout(request):
    logout_user(request)
    return render(request, 'stuff/login.html')

stuff/templates/views/nba.py
from __future__ import print_function

import twitter
from django.shortcuts import render

from stuff.models import Sport, Team
from stuffhub.settings import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_CONSUMER_ACCESS_TOKEN_KEY, \
    TWITTER_CONSUMER_TOKEN_SECRET

TWITTER_API = twitter.Api(consumer_key=TWITTER_CONSUMER_KEY,
                          consumer_secret=TWITTER_CONSUMER_SECRET,
                          access_token_key=TWITTER_CONSUMER_ACCESS_TOKEN_KEY,
                          access_token_secret=TWITTER_CONSUMER_TOKEN_SECRET)

import datetime
from datetime import datetime


def nba(request):
    context = get_nba_teams()
    return render(request, 'stuff/nba.html', context)


def get_nba_teams():
    nba = Sport.objects.filter(abbreviation="NBA").first()
    nba_teams = Team.objects.filter(sport=nba).order_by("abbreviation")
    print(nba_teams)
    context = {
        'nba_teams': nba_teams
    }
    return context


tweets_nba = {}
tweets_nba = set(tweets_nba)
users_nba = {"NBA", "wojespn", "ShamsCharania", "ZachLowe_NBA", "sam_amick", "TheSteinLine", "ChrisBHaynes",
             "davidaldridgedc", "WindhorstESPN"}


def nba_tweets(request):
    print(nba_tweets.__name__)
    print(request)
    print(request.get_full_path())
    for user in users_nba:
        data = TWITTER_API.GetUserTimeline(screen_name=user, count=5)

        for new_tweet in data:
            # print(new_tweet)
            # print(new_tweet.id)
            if not any(new_tweet.id == tweet.id for tweet in tweets_nba):
                tweets_nba.add(new_tweet)

    sorted_tweets_nba = sorted(tweets_nba, key=lambda d: datetime.strptime(d.created_at, '%a %b %d %H:%M:%S %z %Y'),
                               reverse=True)

    print(tweets_nba)
    context = {
        'sport': "nba",
        'tweets': sorted_tweets_nba,
        'users': users_nba
    }

    return render(request, 'stuff/tweets.html', context)

stuff/templates/views/register.py
from django.shortcuts import render


def register(request):
    return render(request, 'stuff/register.html')

stuff/templates/stuff/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Home | StuffHub</title>
    {% load static %}
    {% include "stuff/navbar.html" with active_tab='index' %}
    <link rel="stylesheet" type="text/css" href="{% static 'stuff/css/index.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'stuff/js/scripts.js' %}"></script>
</head>

<body>
{#<div class="embed-responsive embed-responsive-16by9">#}
{#    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/QpZCCRNRjtw"></iframe>#}
{#</div>#}
</body>
</html>

stuff/templates/stuff/influencer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Influencers | StuffHub</title>
    {% load static %}
    {% include "stuff/navbar.html" with active_tab='influencers' %}
    <link rel="stylesheet" type="text/css" href="{% static 'stuff/css/influencer.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'stuff/js/scripts.js' %}"></script>
</head>

<body>
TEST
{{ influencer }}
TEST1
{{ influencer.id }}
TEST2
{{ influencer.first_name }}
TEST3
{{ influencer.last_name }}
{#    {{ % for % }}#}
{#    {{ influencer.id }}#}
{#    {{ influencer.first_name }}#}
{#    {{ influencer.last_name }}#}
{#    {{ influencer.twitter }}#}
{#    {{ influencer.instagram }}#}
{#    {{ influencer.youtube }}#}
{#    {{ influencer.facebook }}#}

</body>
</html>

stuff/templates/stuff/influencers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Influencers | StuffHub</title>
    {% load static %}
    {% include "stuff/navbar.html" with active_tab='influencers' %}
    <link rel="stylesheet" type="text/css" href="{% static 'stuff/css/influencers.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'stuff/js/scripts.js' %}"></script>
</head>

<body>
<section>
    <div class="container">
        <div class="row">
            <h2>Entertainment</h2>
        </div>
        <div class="row">
            {% for influencer in entertainment %}
                {% include "stuff/influencer_card.html" %}
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <h2>Entertainment</h2>
        </div>
        <div class="row">
            {% for influencer in entertainment %}
                {% include "stuff/influencer_card.html" %}
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <h2>Food</h2>
        </div>
        <div class="row">
            {% for influencer in food %}
                {% include "stuff/influencer_card.html" %}
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <h2>Sports & Fitness</h2>
        </div>
        <div class="row">
            {% for influencer in sports_fitness %}
                {% include "stuff/influencer_card.html" %}
            {% endfor %}
        </div>
    </div>
</section>

</div>

</body>
</html>

stuff/templates/stuff/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Log In | StuffHub</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'stuff/css/login.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'stuff/js/scripts.js' %}"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-header">
                        <h1 class="card-title text-center">StuffHub</h1>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Log In</h5>
                        <form class="form-signin" action="{% url 'stuff:login' %}" method="POST">
                            {% comment %} <form action="{% url 'stuff:add_twitter_user' sport %}" method="POST" {% endcomment %}
                            {% csrf_token %}
                            {% comment %} {{ form.as_p }} {% endcomment %}
                            <div class="form-label-group">
                                <input type="email" id="email" name="email" class="form-control" placeholder="Email Address" required autofocus>
                                <label for="email">Email address</label>
                            </div>
                            <div class="form-label-group">
                                <input type="password" id="password" name="password"  class="form-control" placeholder="Password" required>
                                <label for="inputPassword">Password</label>
                            </div>
                            <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" value="login">Log in</button>
                            <hr class="my-4">
                        </form>
                        <a class="btn btn-md btn-outline-primary btn-block text-uppercase" id="Register"
                           href="/stuff/register">Register</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

stuff/templates/stuff/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'stuff/css/navbar.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/2db55a7b3c.js"></script>
</head>

<body>
    <div class="topnav">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="#">StuffHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item {% if active_tab == 'index' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'stuff:index' %}">
                                <i class="fa fa-home"></i> Home <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item {% if active_tab == 'influencers' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'stuff:influencers' %}">
                                <i class="fas fa-user-check"></i> Influencers
                            </a>
                        </li>
                        <li class="nav-item dropdown {% if active_tab == 'nba' %}active{% endif %}">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-basketball-ball"></i> NBA
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'stuff:nba' %}">
                                    <i class="fas fa-users"></i> Teams
                                </a>
                                <a class="dropdown-item" href="{% url 'stuff:nba_tweets' %}">
                                    <i class="fab fa-twitter"></i> Tweets
                                </a>
                                {#                        <div class="dropdown-divider"></div>#}
                                {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                            </div>
                        </li>
                        <li class="nav-item dropdown {% if active_tab == 'mlb' %}active{% endif %}">
                            <a class="nav-link dropdown-toggle" href="{% url 'stuff:mlb' %}" id="navbarDropdown"
                               role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-baseball-ball"></i> MLB
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'stuff:mlb' %}">
                                    <i class="fas fa-users"></i> Teams
                                </a>
                                <a class="dropdown-item" href="{% url 'stuff:mlb_tweets' %}">
                                    <i class="fab fa-twitter"></i> Tweets
                                </a>
                                {#                        <div class="dropdown-divider"></div>#}
                                {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                            </div>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0 bg-light" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                        <form class="form-inline my-2 my-lg-0" action="{% url 'stuff:logout' %}">
                            <button class="btn btn-danger my-2 my-sm-0" type="submit">Logout</button>
                        </form>
                    {% else %}
                        <div><a class="btn btn-light my-2 my-sm-0" id="Register" href="/stuff/register">Register</a>
                        </div>

                        <div><a class="btn btn-success my-2 my-sm-0" id="Login" href="/stuff/login">Login</a></div>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
    <div class="godown" id="godown"></div>
</body>
</html>