faves/urls.py
from django.urls import path

from .templates.views import *

app_name = 'faves'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),

    path('', index, name='index'),
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
    path('influencers', influencers, name='influencers'),
    path('influencers/<str:influencer_id>', influencer, name='influencer'),
    path('nba', nba, name='nba'),
    path('nba/tweets', nba_tweets, name='nba_tweets'),
    path('nba/tweets/<str:sport>', add_twitter_user, name='add_twitter_user'),
    path('mlb', mlb, name='mlb'),
    path('mlb/tweets', mlb_tweets, name='mlb_tweets'),
    path('mlb/tweets/<str:sport>', add_twitter_user, name='add_twitter_user'),
    path('mlb/<str:team_name>', mlb_team, name='mlb_team'),

    # path('mlb/tweets/<str:user>', views.add_twitter_user, name='add_twitter_user'),
    #path('get_teams/', views.get_teams, name='get_teams'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^stats/', include('stats.urls')), #this line added
    url(r'^detection/', include('detection.urls')), #this line added
    url(r'^polls/', include('polls.urls')), #this line added
    url(r'^admin/', admin.site.urls),
]

stats/urls.py
from django.urls import path
from . import views

app_name = 'stats'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),

    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('nba/', views.nba, name='nba'),
    path('nba/tweets', views.nba_tweets, name='nba_tweets'),
    path('nba/tweets/<str:sport>/', views.add_twitter_user, name='add_twitter_user'),
    path('mlb/', views.mlb, name='mlb'),
    path('mlb/tweets', views.mlb_tweets, name='mlb_tweets'),
    path('mlb/tweets/<str:sport>/', views.add_twitter_user, name='add_twitter_user'),
    path('mlb/<str:team_name>/', views.mlb_team, name='mlb_team'),

    # path('mlb/tweets/<str:user>', views.add_twitter_user, name='add_twitter_user'),
    #path('get_teams/', views.get_teams, name='get_teams'),
]

faves/templates/views/login.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def login(request):
    print(login.__name__)
    print(request)
    print(request.get_full_path())
    if request.method == 'POST':
        try:
            user = authenticate(email=request.POST.get('email', None), password=request.POST.get('password', None))
            if user is not None:
                print("Logging in")
                login_user(request, user)
                return HttpResponseRedirect(reverse('faves:index'))
            else:
                print("Cant log in")
                return HttpResponseRedirect(reverse('faves:login'))

        except Exception as err:
            print(err)
            for i in err.message:
                print(i)

    return render(request, 'faves/login.html')

faves/templates/views/mlb.py
from __future__ import print_function

import twitter
from django.shortcuts import render

from faves.models import Sport, Team
from myfaves.settings import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_CONSUMER_ACCESS_TOKEN_KEY, \
    TWITTER_CONSUMER_TOKEN_SECRET

TWITTER_API = twitter.Api(consumer_key=TWITTER_CONSUMER_KEY,
                          consumer_secret=TWITTER_CONSUMER_SECRET,
                          access_token_key=TWITTER_CONSUMER_ACCESS_TOKEN_KEY,
                          access_token_secret=TWITTER_CONSUMER_TOKEN_SECRET)

import datetime
from datetime import datetime

import mlbgame


def mlb(request):
    # mlb_teams = mlbgame.teams()
    context = {}
    context.update(get_mlb_teams())
    context.update(get_mlb_games_today())
    return render(request, 'faves/mlb.html', context)


def mlb_team(request, team_name):
    # mlb_teams = mlbgame.teams()
    print("TESTTTTTTTTTTTTTTTTT mlb_team: " + team_name)
    mlb_teams = get_mlb_teams()
    this_team = None
    for team in mlb_teams['mlb_teams']:
        if team.nickname.lower() == team_name:
            this_team = team
    print(this_team)
    context = {
        "team": this_team

    }
    return render(request, 'faves/mlb_team.html', context)


def get_mlb_teams():
    mlb = Sport.objects.filter(abbreviation="MLB").first()
    mlb_teams = Team.objects.filter(sport=mlb)

    print(mlb_teams)
    context = {
        'mlb_teams': mlb_teams
    }
    print("........................................")
    return context


def get_mlb_games_today():
    now = datetime.now()
    day = mlbgame.day(now.year, now.month, now.day)
    day.sort(key=lambda d: datetime.strptime(d.game_start_time, '%I:%M %p'), reverse=False)

    for game in day:
        print(game.game_id)
    # print(game.game_id)
    # test = mlbgame.box_score(game.game_id)
    # mlbgame.overview(game.game_id)
    # mlbgame.players(game.game_id)
    # mlbgame.team_stats(game.game_id)
    # mlbgame.player_stats(game.game_id)
    # mlbgame.game_events(game.game_id)

    print(day)
    context = {
        "games_today": day

    }
    return context


tweets_mlb = {}
tweets_mlb = set(tweets_mlb)
users_mlb = {"MLB", "Yankees", "mlbtraderumors", "Ken_Rosenthal", "JonHeymanCBS", "Buster_ESPN"}


def mlb_tweets(request):
    print(mlb_tweets.__name__)
    print(request)
    print(request.get_full_path())
    for user in users_mlb:
        data = TWITTER_API.GetUserTimeline(screen_name=user, count=5)

        for new_tweet in data:
            # print(new_tweet)
            # print(new_tweet.id)
            if not any(new_tweet.id == tweet.id for tweet in tweets_mlb):
                tweets_mlb.add(new_tweet)

    sorted_tweets_mlb = sorted(tweets_mlb, key=lambda d: datetime.strptime(d.created_at, '%a %b %d %H:%M:%S %z %Y'),
                               reverse=True)

    print(tweets_mlb)
    context = {
        'sport': "mlb",
        'tweets': sorted_tweets_mlb,
        'users': users_mlb
    }

    return render(request, 'faves/tweets.html', context)

faves/templates/views/nba.py
from __future__ import print_function

import twitter
from django.shortcuts import render

from faves.models import Sport, Team
from myfaves.settings import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_CONSUMER_ACCESS_TOKEN_KEY, \
    TWITTER_CONSUMER_TOKEN_SECRET

TWITTER_API = twitter.Api(consumer_key=TWITTER_CONSUMER_KEY,
                          consumer_secret=TWITTER_CONSUMER_SECRET,
                          access_token_key=TWITTER_CONSUMER_ACCESS_TOKEN_KEY,
                          access_token_secret=TWITTER_CONSUMER_TOKEN_SECRET)

import datetime
from datetime import datetime


def nba(request):
    context = get_nba_teams()
    return render(request, 'faves/nba.html', context)


def get_nba_teams():
    nba = Sport.objects.filter(abbreviation="NBA").first()
    nba_teams = Team.objects.filter(sport=nba).order_by("abbreviation")
    print(nba_teams)
    context = {
        'nba_teams': nba_teams
    }
    return context


tweets_nba = {}
tweets_nba = set(tweets_nba)
users_nba = {"NBA", "wojespn", "ShamsCharania", "ZachLowe_NBA", "sam_amick", "TheSteinLine", "ChrisBHaynes",
             "davidaldridgedc", "WindhorstESPN"}


def nba_tweets(request):
    print(nba_tweets.__name__)
    print(request)
    print(request.get_full_path())
    for user in users_nba:
        data = TWITTER_API.GetUserTimeline(screen_name=user, count=5)

        for new_tweet in data:
            # print(new_tweet)
            # print(new_tweet.id)
            if not any(new_tweet.id == tweet.id for tweet in tweets_nba):
                tweets_nba.add(new_tweet)

    sorted_tweets_nba = sorted(tweets_nba, key=lambda d: datetime.strptime(d.created_at, '%a %b %d %H:%M:%S %z %Y'),
                               reverse=True)

    print(tweets_nba)
    context = {
        'sport': "nba",
        'tweets': sorted_tweets_nba,
        'users': users_nba
    }

    return render(request, 'faves/tweets.html', context)

faves/templates/views/register.py
from django.shortcuts import render


def register(request):
    return render(request, 'faves/register.html')

stuff/templates/views/login.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def login(request):
    print(login.__name__)
    print(request)
    print(request.get_full_path())
    if request.method == 'POST':
        try:
            user = authenticate(email=request.POST.get('email', None), password=request.POST.get('password', None))
            if user is not None:
                login_user(request, user)
                return HttpResponseRedirect(reverse('stuff:index'))
            else:
                return HttpResponseRedirect(reverse('stuff:login_view'))

        except Exception as err:
            print(err.message)
            for i in err.message:
                print(i)

    return render(request, 'stuff/login.html')

stuff/templates/views/mlb.py
from __future__ import print_function

import twitter
from django.shortcuts import render

from stuff.models import Sport, Team
from stuffhub.settings import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_CONSUMER_ACCESS_TOKEN_KEY, \
    TWITTER_CONSUMER_TOKEN_SECRET

TWITTER_API = twitter.Api(consumer_key=TWITTER_CONSUMER_KEY,
                          consumer_secret=TWITTER_CONSUMER_SECRET,
                          access_token_key=TWITTER_CONSUMER_ACCESS_TOKEN_KEY,
                          access_token_secret=TWITTER_CONSUMER_TOKEN_SECRET)

import datetime
from datetime import datetime

import mlbgame


def mlb(request):
    # mlb_teams = mlbgame.teams()
    context = {}
    context.update(get_mlb_teams())
    context.update(get_mlb_games_today())
    return render(request, 'stuff/mlb.html', context)


def mlb_team(request, team_name):
    # mlb_teams = mlbgame.teams()
    print("TESTTTTTTTTTTTTTTTTT mlb_team: " + team_name)
    mlb_teams = get_mlb_teams()
    this_team = None
    for team in mlb_teams['mlb_teams']:
        if team.nickname.lower() == team_name:
            this_team = team
    print(this_team)
    context = {
        "team": this_team

    }
    return render(request, 'stuff/mlb_team.html', context)


def get_mlb_teams():
    mlb = Sport.objects.filter(abbreviation="MLB").first()
    mlb_teams = Team.objects.filter(sport=mlb)

    print(mlb_teams)
    context = {
        'mlb_teams': mlb_teams
    }
    print("........................................")
    return context


def get_mlb_games_today():
    now = datetime.now()
    day = mlbgame.day(now.year, now.month, now.day)
    day.sort(key=lambda d: datetime.strptime(d.game_start_time, '%I:%M %p'), reverse=False)

    for game in day:
        print(game.game_id)
    # print(game.game_id)
    # test = mlbgame.box_score(game.game_id)
    # mlbgame.overview(game.game_id)
    # mlbgame.players(game.game_id)
    # mlbgame.team_stats(game.game_id)
    # mlbgame.player_stats(game.game_id)
    # mlbgame.game_events(game.game_id)

    print(day)
    context = {
        "games_today": day

    }
    return context


tweets_mlb = {}
tweets_mlb = set(tweets_mlb)
users_mlb = {"MLB", "Yankees", "mlbtraderumors", "Ken_Rosenthal", "JonHeymanCBS", "Buster_ESPN"}


def mlb_tweets(request):
    print(mlb_tweets.__name__)
    print(request)
    print(request.get_full_path())
    for user in users_mlb:
        data = TWITTER_API.GetUserTimeline(screen_name=user, count=5)

        for new_tweet in data:
            # print(new_tweet)
            # print(new_tweet.id)
            if not any(new_tweet.id == tweet.id for tweet in tweets_mlb):
                tweets_mlb.add(new_tweet)

    sorted_tweets_mlb = sorted(tweets_mlb, key=lambda d: datetime.strptime(d.created_at, '%a %b %d %H:%M:%S %z %Y'),
                               reverse=True)

    print(tweets_mlb)
    context = {
        'sport': "mlb",
        'tweets': sorted_tweets_mlb,
        'users': users_mlb
    }

    return render(request, 'stuff/tweets.html', context)

stuff/templates/views/nba.py
from __future__ import print_function

import twitter
from django.shortcuts import render

from stuff.models import Sport, Team
from stuffhub.settings import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_CONSUMER_ACCESS_TOKEN_KEY, \
    TWITTER_CONSUMER_TOKEN_SECRET

TWITTER_API = twitter.Api(consumer_key=TWITTER_CONSUMER_KEY,
                          consumer_secret=TWITTER_CONSUMER_SECRET,
                          access_token_key=TWITTER_CONSUMER_ACCESS_TOKEN_KEY,
                          access_token_secret=TWITTER_CONSUMER_TOKEN_SECRET)

import datetime
from datetime import datetime


def nba(request):
    context = get_nba_teams()
    return render(request, 'stuff/nba.html', context)


def get_nba_teams():
    nba = Sport.objects.filter(abbreviation="NBA").first()
    nba_teams = Team.objects.filter(sport=nba).order_by("abbreviation")
    print(nba_teams)
    context = {
        'nba_teams': nba_teams
    }
    return context


tweets_nba = {}
tweets_nba = set(tweets_nba)
users_nba = {"NBA", "wojespn", "ShamsCharania", "ZachLowe_NBA", "sam_amick", "TheSteinLine", "ChrisBHaynes",
             "davidaldridgedc", "WindhorstESPN"}


def nba_tweets(request):
    print(nba_tweets.__name__)
    print(request)
    print(request.get_full_path())
    for user in users_nba:
        data = TWITTER_API.GetUserTimeline(screen_name=user, count=5)

        for new_tweet in data:
            # print(new_tweet)
            # print(new_tweet.id)
            if not any(new_tweet.id == tweet.id for tweet in tweets_nba):
                tweets_nba.add(new_tweet)

    sorted_tweets_nba = sorted(tweets_nba, key=lambda d: datetime.strptime(d.created_at, '%a %b %d %H:%M:%S %z %Y'),
                               reverse=True)

    print(tweets_nba)
    context = {
        'sport': "nba",
        'tweets': sorted_tweets_nba,
        'users': users_nba
    }

    return render(request, 'stuff/tweets.html', context)

stuff/templates/views/register.py
from django.shortcuts import render


def register(request):
    return render(request, 'stuff/register.html')

stats/templates/stats/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Home | StuffHub</title>
    {% load static %}
    {% include "stats/navbar.html" with active_tab='index' %}
    <link rel="stylesheet" type="text/css" href="{% static 'stats/css/index.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'stats/js/scripts.js' %}"></script>
</head>

<body>

</body>
</html>

stats/templates/stats/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Log In | StuffHub</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'stats/css/login.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'stats/js/scripts.js' %}"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-header">
                        <h1 class="card-title text-center">StuffHub</h1>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Log In</h5>
                        <form class="form-signin" action="{% url 'stats:login' %}" method="POST" >
                        {% comment %} <form action="{% url 'stats:add_twitter_user' sport %}" method="POST" {% endcomment %}
                            {% csrf_token %}
                            {% comment %} {{ form.as_p }} {% endcomment %}
                            <div class="form-label-group">
                                <input type="email" id="email" name="email" class="form-control" placeholder="Email Address" required autofocus>
                                <label for="email">Email address</label>
                            </div>
                            <div class="form-label-group">
                                <input type="password" id="password" name="password"  class="form-control" placeholder="Password" required>
                                <label for="inputPassword">Password</label>
                            </div>
                            <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" value="login">Log in</button>
                            <hr class="my-4">
                        </form>
                        <a class="btn btn-md btn-outline-primary btn-block text-uppercase" id="Register" href="/stats/register">Register</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

stats/templates/stats/mlb_team.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {{ team | title }} | StuffHub </title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'stats/css/index.css' %}">
</head>

<body>
    {% include "stats/navbar.html" with active_tab='mlb' %}
    {{ team }}
</body>
</html>

stats/templates/stats/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'stats/css/navbar.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/2db55a7b3c.js"></script>
</head>

<body>
    <div class="topnav">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="#">StuffHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item {% if active_tab == 'index' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'stats:index' %}">
                                <i class="fa fa-home"></i> Home <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown {% if active_tab == 'nba' %}active{% endif %}">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-basketball-ball"></i> NBA
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'stats:nba' %}">
                                    <i class="fas fa-users"></i> Teams
                                </a>
                                <a class="dropdown-item" href="{% url 'stats:nba_tweets' %}">
                                    <i class="fab fa-twitter"></i> Tweets
                                </a>
                                {#                        <div class="dropdown-divider"></div>#}
                                {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                            </div>
                        </li>
                        <li class="nav-item dropdown {% if active_tab == 'mlb' %}active{% endif %}">
                            <a class="nav-link dropdown-toggle" href="{% url 'stats:mlb' %}" id="navbarDropdown"
                               role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-baseball-ball"></i> MLB
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'stats:mlb' %}">
                                    <i class="fas fa-users"></i> Teams
                                </a>
                                <a class="dropdown-item" href="{% url 'stats:mlb_tweets' %}">
                                    <i class="fab fa-twitter"></i> Tweets
                                </a>
                                {#                        <div class="dropdown-divider"></div>#}
                                {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                            </div>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0 bg-light" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                        <form class="form-inline my-2 my-lg-0" action="{% url 'stats:logout' %}">
                            <button class="btn btn-danger my-2 my-sm-0" type="submit">Logout</button>
                        </form>
                    {% else %}
                        <div> <a class="btn btn-light my-2 my-sm-0" id="Register" href="/stats/register">Register</a></div>
                        
                        <div><a class="btn btn-success my-2 my-sm-0" id="Login" href="/stats/login">Login</a> </div>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
    <div class="godown" id="godown"></div>
</body>
</html>

stats/templates/stats/nba.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title> NBA | StuffHub</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'stats/css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stats/css/nba.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stats/css/flip_cards.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'stats/js/scripts.js' %}"></script>
</head>

<body>
    {% include "stats/navbar.html" with active_tab='nba' %}
    <div class="container w-75">
        <div class="container-fluid">
            <div class="row h-100 justify-content-center align-items-center">
                {% for nba_team in nba_teams %}
                     <div class="d-flex flex-column">
                        <div class="flip-card" data-content={{ nba_team.abbreviation }}>
                            {#                    <div class="card-image">#}
                            {#                                                <img src="{% static "images/hawks.jpg" %}">#}
                            {#                    </div>#}
                            <div class="flip-card-inner" data-content={{ nba_team.abbreviation }}>
                                <div class="flip-card-front">
                                    <img id="team-logo-{{ nba_team.abbreviation|lower }}"
                                         class="team-logo"
                                         src="{% static 'images/nba/' %}{{ nba_team.abbreviation|lower }}.jpg"
                                         data-src="{{ nba_team.abbreviation|lower }}">
                                    {#                            <canvas id="myCanvas-{{ nba_team.nickname|lower }}"#}
                                    {#                                    data-src="{{ nba_team.nickname|lower }}"#}
                                    {#                                    style="width:300px;height:300px;"></canvas>#}
                                    {#                            <script type="text/javascript" src="{% static 'stats/js/logos.js ' %}"></script>#}
                                    {#                            <script type="text/javascript"> var static_url = "{% static 'images/'%}{{ nba_team.nickname|lower}}.jpg %}"; setTeamLogo("{{ nba_team.nickname|lower}}","{% static 'images/{{ nba_team.nickname|lower}}.jpg' %}" );#}
                                    {#                             </script>#}

                                </div>
                                <div class="flip-card-back">
                                    <a href="https://www.nba.com/{{ nba_team.nickname|lower }}"
                                       target="_blank">
                                        <h3 class="card-title" data-content={{ nba_team.abbreviation }}>
                                            {{ nba_team.full_name }}
                                        </h3>
                                        <p class="card-title" data-content={{ nba_team.abbreviation }}>
                                            ({{ nba_team.abbreviation }})
                                        </p>
                                    </a>
                                    {#                            <p class="card-text" data-content={{ nba_team.abbsreviation }}></p>#}
                                    {% for game in nba_team.games %}
                                        <a class="box-score-url" id="box-score-url-{{ nba_team.abbreviation }}-{{ game.game_id }}" href="#"
                                           target="_blank">
                                            <p class="card-text">{{ game.date }} {{ game.away_team_name }}
                                                @ {{ game.home_team_name }}</p>
                                        </a>
                                        <script type="text/javascript" src="{% static 'stats/js/logos.js ' %}"></script>
                                        <script type="text/javascript"> getBoxScoreURL("{{ game.game_id }}", "{{ game.date }}", "{{ game.home_team_name }}", "box-score-url-{{ nba_team.abbreviation }}-{{ game.game_id }}"); </script>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
    {#        </div>#}
        </div>
    </div>
</body>
</html>